openapi: 3.0.0
paths:
  /auth/login:
    post:
      operationId: AppController_login
      parameters: []
      responses:
        "201":
          description: ""
      tags:
        - auth
  /user/{id}:
    get:
      operationId: getOneBaseUserControllerUserEntity
      summary: Retrieve a single UserEntity
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
        - name: fields
          description: >-
            Selects resource fields. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#select"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
          style: form
          explode: false
        - name: join
          description: >-
            Adds relational resources. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#join"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
        - name: cache
          description: >-
            Reset cache (if was enabled). <a
            href="https://github.com/nestjsx/crud/wiki/Requests#cache"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: integer
            minimum: 0
            maximum: 1
      responses:
        "200":
          description: Get one base response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserEntity"
      tags: &ref_0
        - user
      security: &ref_1
        - bearer: []
    patch:
      operationId: updateOneBaseUserControllerUserEntity
      summary: Update a single UserEntity
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserEntity"
      responses:
        "200":
          description: Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserEntity"
      tags: *ref_0
      security: *ref_1
    put:
      operationId: replaceOneBaseUserControllerUserEntity
      summary: Replace a single UserEntity
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserEntity"
      responses:
        "200":
          description: Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserEntity"
      tags: *ref_0
      security: *ref_1
    delete:
      operationId: deleteOneBaseUserControllerUserEntity
      summary: Delete a single UserEntity
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        "200":
          description: Delete one base response
      tags: *ref_0
      security: *ref_1
  /user:
    get:
      operationId: getManyBaseUserControllerUserEntity
      summary: Retrieve multiple UserEntities
      parameters:
        - name: fields
          description: >-
            Selects resource fields. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#select"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
          style: form
          explode: false
        - name: s
          description: >-
            Adds search condition. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#search"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: string
        - name: filter
          description: >-
            Adds filter condition. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#filter"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
        - name: or
          description: >-
            Adds OR condition. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#or"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
        - name: sort
          description: >-
            Adds sort by field. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#sort"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
        - name: join
          description: >-
            Adds relational resources. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#join"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
        - name: limit
          description: >-
            Limit amount of resources. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#limit"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: integer
        - name: offset
          description: >-
            Offset amount of resources. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#offset"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: integer
        - name: page
          description: >-
            Page portion of resources. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#page"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: integer
        - name: cache
          description: >-
            Reset cache (if was enabled). <a
            href="https://github.com/nestjsx/crud/wiki/Requests#cache"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: integer
            minimum: 0
            maximum: 1
      responses:
        "200":
          description: Get paginated response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetManyUserEntityResponseDto"
      tags: *ref_0
      security: *ref_1
    post:
      operationId: createOneBaseUserControllerUserEntity
      summary: Create a single UserEntity
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserEntity"
      responses:
        "201":
          description: Get create one base response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserEntity"
      tags: *ref_0
      security: *ref_1
  /user/bulk:
    post:
      operationId: createManyBaseUserControllerUserEntity
      summary: Create multiple UserEntities
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateManyUserEntityDto"
      responses:
        "201":
          description: Get create many base response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserEntity"
      tags: *ref_0
      security: *ref_1
  /post:
    post:
      operationId: createOneBasePostControllerPostEntity
      summary: Create a single PostEntity
      parameters: []
      responses:
        "201":
          description: Get create one base response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostEntity"
      tags: &ref_2
        - post
    get:
      operationId: getManyBasePostControllerPostEntity
      summary: Retrieve multiple PostEntities
      parameters:
        - name: fields
          description: >-
            Selects resource fields. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#select"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
          style: form
          explode: false
        - name: s
          description: >-
            Adds search condition. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#search"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: string
        - name: filter
          description: >-
            Adds filter condition. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#filter"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
        - name: or
          description: >-
            Adds OR condition. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#or"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
        - name: sort
          description: >-
            Adds sort by field. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#sort"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
        - name: join
          description: >-
            Adds relational resources. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#join"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
        - name: limit
          description: >-
            Limit amount of resources. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#limit"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: integer
        - name: offset
          description: >-
            Offset amount of resources. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#offset"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: integer
        - name: page
          description: >-
            Page portion of resources. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#page"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: integer
        - name: cache
          description: >-
            Reset cache (if was enabled). <a
            href="https://github.com/nestjsx/crud/wiki/Requests#cache"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: integer
            minimum: 0
            maximum: 1
      responses:
        "200":
          description: Get paginated response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetManyPostEntityResponseDto"
      tags: *ref_2
  /post/{id}:
    patch:
      operationId: updateOneBasePostControllerPostEntity
      summary: Update a single PostEntity
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        "200":
          description: Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostEntity"
      tags: *ref_2
    get:
      operationId: getOneBasePostControllerPostEntity
      summary: Retrieve a single PostEntity
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
        - name: fields
          description: >-
            Selects resource fields. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#select"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
          style: form
          explode: false
        - name: join
          description: >-
            Adds relational resources. <a
            href="https://github.com/nestjsx/crud/wiki/Requests#join"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
        - name: cache
          description: >-
            Reset cache (if was enabled). <a
            href="https://github.com/nestjsx/crud/wiki/Requests#cache"
            target="_blank">Docs</a>
          required: false
          in: query
          schema:
            type: integer
            minimum: 0
            maximum: 1
      responses:
        "200":
          description: Get one base response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostEntity"
      tags: *ref_2
    put:
      operationId: replaceOneBasePostControllerPostEntity
      summary: Replace a single PostEntity
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostEntity"
      responses:
        "200":
          description: Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostEntity"
      tags: *ref_2
    delete:
      operationId: deleteOneBasePostControllerPostEntity
      summary: Delete a single PostEntity
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        "200":
          description: Delete one base response
      tags: *ref_2
  /post/bulk:
    post:
      operationId: createManyBasePostControllerPostEntity
      summary: Create multiple PostEntities
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateManyPostEntityDto"
      responses:
        "201":
          description: Get create many base response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PostEntity"
      tags: *ref_2
info:
  title: "@dataui/crud-typeorm"
  description: "@dataui/crud-typeorm"
  version: "1.0"
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    GetManyUserEntityResponseDto:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/UserEntity"
        count:
          type: number
        total:
          type: number
        page:
          type: number
        pageCount:
          type: number
      required:
        - data
        - count
        - total
        - page
        - pageCount
    UserEntity:
      type: object
      properties: {}
    CreateManyUserEntityDto:
      type: object
      properties:
        bulk:
          type: array
          items:
            $ref: "#/components/schemas/UserEntity"
      required:
        - bulk
    GetManyPostEntityResponseDto:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/PostEntity"
        count:
          type: number
        total:
          type: number
        page:
          type: number
        pageCount:
          type: number
      required:
        - data
        - count
        - total
        - page
        - pageCount
    PostEntity:
      type: object
      properties: {}
    CreateManyPostEntityDto:
      type: object
      properties:
        bulk:
          type: array
          items:
            $ref: "#/components/schemas/PostEntity"
      required:
        - bulk
